name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python environment
      uses: actions/setup-python@v3.1
    - name: List files in repo
      run: ls -la
    - name: Install requirements
      working-directory: Ch04/04_02
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      working-directory: Ch04/04_02
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit tests
      working-directory: Ch04/04_02
      run: |
        python -m unittest --verbose --failfast
